/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import OBJ.SanPham;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class frmSanPhamTemplate extends javax.swing.JPanel {

    /**
     * Creates new form frmSanPhamTemplate
     */
    private DefaultTableModel defaultTableModel;
    SanPham sp = new SanPham();
    ArrayList<SanPham> listSP = new ArrayList<>();
    public frmSanPhamTemplate() {
        initComponents();
    }
    public void loadFile() {
        try {
            BufferedReader br = null;
            FileReader fr = null;
            listSP = new ArrayList<>(); //lưu ý
            fr = new FileReader("sanpham.txt");
            br = new BufferedReader(fr);
            String s = null;
            
            try {
                while ((s = br.readLine()) != null) {
                    //Cắt chuỗi:
                    String arr[] = s.split("\t");
                    //Khởi tạo
                    SanPham sp = new SanPham();
                    sp.setMaSanPham(arr[0]);
                    sp.setTenSanPham(arr[1]);
                    sp.setDonViTinh(arr[2]);
                    sp.setTenNSX(arr[3]);
                    sp.setGiaNhap(arr[4]);
                    sp.setGiaBan(arr[5]);
                    sp.setSoLuong(Integer.parseInt(arr[6]));
                    listSP.add(sp);
                }
            } catch (IOException ex) {
                Logger.getLogger(frmSanPhamTemplate.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(frmSanPhamTemplate.class.getName()).log(Level.SEVERE, null, ex);
        }
           

    }

    public void saveFile() {

        try {
            BufferedWriter bw = null; //Khởi tạo
            FileWriter fw = null; //Khởi tạo
            String data = ""; //Tạo một string data bằng rỗng.
            for (int i = 0; i < listSP .size(); i++) {
                String row = ""; //tạo hàng rỗng
                row = row + listSP.get(i).getMaSanPham()+ "\t";
                row = row + listSP.get(i).getTenSanPham()+ "\t";
                row = row + listSP.get(i).getDonViTinh()+ "\t";
                row = row + listSP.get(i).getTenNSX()+ "\t";
                row = row + listSP.get(i).getGiaNhap()+ "\t";
                row = row + listSP.get(i).getGiaBan()+ "\t";
                row = row + listSP.get(i).getSoLuong()+ "\n";
                data += row;
            }
            fw = new FileWriter("sanpham.txt");
            bw = new BufferedWriter(fw);
            bw.write(data);
            bw.close();
        } catch (IOException ex) {
            Logger.getLogger(frmSanPhamTemplate.class.getName()).log(Level.SEVERE, null, ex);
        }
        

    }
    
    private void getData(ArrayList<SanPham> listSP) {
        defaultTableModel = new DefaultTableModel();
        defaultTableModel.addColumn("Mã SP");
        defaultTableModel.addColumn("Tên SP");
        defaultTableModel.addColumn("Đơn vi tính");
        defaultTableModel.addColumn("Tên NSX");
        defaultTableModel.addColumn("Giá nhập");
        defaultTableModel.addColumn("Giá bán");
        defaultTableModel.addColumn("Số lượng");

        for (SanPham obj : listSP) {
            Vector vector = new Vector();
            vector.add(obj.getMaSanPham());
            vector.add(obj.getTenSanPham());
            vector.add(obj.getDonViTinh());
            vector.add(obj.getTenNSX());
            vector.add(obj.getGiaNhap());
            vector.add(obj.getGiaBan());
            vector.add(obj.getSoLuong());
            defaultTableModel.addRow(vector);
        }
        tbl_sanpham.setModel(defaultTableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_sanpham = new javax.swing.JTable();

        tbl_sanpham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_sanpham);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 939, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(266, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_sanpham;
    // End of variables declaration//GEN-END:variables
}
